### ISSUE TITLE
Paginating Results

### ISSUE THREAD

**Issue by cjmellor** [staudenmeir/laravel-adjacency-list#110]
_Not really an "issue" per se, but there is no discussion board_

I'd like to paginate my results from this package and while technically I have got it working, the queries it's using seem avoidable, but haven't had success in reducing them.

Is there a simpler non-documented way of paginating the data?

I am doing it like so:

```php
Section::tree()->paginate(perPage: config(key: 'app.per_page')),
```

But it is giving me a lot of unnecessary queries (I believe)

<img width="721" alt="image" src="https://user-images.githubusercontent.com/1848476/172168998-20beef56-a2ba-42ef-a371-9c256cd04380.png">

Other techniques I have tried have ended up been worse 😅

Any suggestions?

Thanks.

**Comment by staudenmeir** [comment]
Please share the `Section` model.

The pagination should only run two queries, I think the rest is coming from somewhere else.

How many queries do you see with this?

```php
DB::enableQueryLog();

Section::tree()->paginate(perPage: config(key: 'app.per_page'));

dd(DB::getQueryLog());
```

**Comment by staudenmeir** [comment]
Ok, so the pagination only runs two queries as expected. What else are you doing in this controller method?

I think you were mislead a bit about the queries' origin because they all come from the `BuildsAdjacencyListQueries` trait. Due to the way the package integrates into the recursive model (e.g. `Section`), _all_ queries on the model now originate from this trait, even when they don't have to do anything with recursiveness (like `Section::find(1)`).

**Comment by cjmellor** [comment]
I see. Understandable. I'm fine with it as is, I'm just a sucker for getting as lesser queries as possible 😅

Thanks @staudenmeir
