### ISSUE TITLE
hasManyOfDescendantsAndSelf error Undefined array key 0

### ISSUE THREAD

**Issue by YouMixx** [staudenmeir/laravel-adjacency-list#161]
The function "hasManyOfDescendantsAndSelf" causes the error "Undefined array key 0" if there is no nesting.

If at least one element has a child, there is no error. But if the humidity is zero and all the loaded elements are parent elements, an error is caused.

**Comment by YouMixx** [comment]
This my function
![image](https://user-images.githubusercontent.com/89249508/225892597-df50b702-e692-4805-be7d-49f964aff3b8.png)

**Comment by YouMixx** [comment]
This is the "Comments" table. Here, as you can see, there are child elements. In this case, there will be no error.![image](https://user-images.githubusercontent.com/89249508/225892823-b6b625a3-34a3-4753-9f0f-c3190ed21e7f.png)

But if the table is like this, i.e. there will be no child elements, the error I mentioned occurs.
![image](https://user-images.githubusercontent.com/89249508/225893048-f612f737-debd-488c-b79d-28cdf34c03d2.png)

**Comment by YouMixx** [comment]
That's what ChatGPT said)

> The error occurs because the staudenmeir/laravel-adjacency-list library uses the key By method to group child comments by their parent comment. However, if the parent comment has no child comments, the keyBy method will return an empty array, which will cause the error "Undefined array key 0".

**Comment by staudenmeir** [comment]
Please share the whole `Comment` model.

> Please also share the whole error with its stacktrace.

I need to see where the error is coming from.

**Comment by YouMixx** [comment]
`<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Staudenmeir\LaravelAdjacencyList\Eloquent\HasRecursiveRelationships;

class Comment extends Model
{
    use HasFactory, HasRecursiveRelationships;

    protected $fillable = [
        'user_id',
        'review_id',
        'comment_id',
        'content',
        'status',
        'reason',
        'anonym_name',
        'ip',
    ];

    public function getParentKeyName()
    {
        return 'comment_id';
    }

    public function user()
    {
        return $this->belongsTo(User::class);
    }

    public function review()
    {
        return $this->belongsTo(Review::class);
    }

    public function childrenComments()
    {
        return $this->hasMany(Comment::class);
    }

    public function parentComment()
    {
        return $this->belongsTo(Comment::class, 'comment_id');
    }

    public function recursiveComments()
    {
        return $this->hasMany(Comment::class, 'comment_id', 'id')->with('recursiveComments', function ($query) {
            $query->with('user');
        });
        // return $this->hasManyOfDescendantsAndSelf(Comment::class);
    }
}
`

**Comment by staudenmeir** [comment]
I think there's a misunderstanding here: `hasManyOfDescendantsAndSelf()` is meant for getting related models. In the [example](https://github.com/staudenmeir/laravel-adjacency-list#hasmanyofdescendants), it's used to retrieve related posts from the recursive `User` model.

It looks like the relationships you need are actually already included in the package:
https://github.com/staudenmeir/laravel-adjacency-list#included-relationships

Use `descendantsAndSelf()` instead of `recursiveComments()`:

```php
$review->comments()->with('descendantsAndSelf')->...
```

You can also remove `childrenComments()` and `parentComment()` and use `children()`/`parent()` instead.

**Comment by staudenmeir** [comment]
Please update the package to the latest version and see if #162 also fixed your issue.

**Comment by deepakchhapru** [comment]
@staudenmeir If I call relation "descendants" with where condition instead of "descendantsAndSelf". This error occurs.

Reason: inside Staudenmeir\LaravelAdjacencyList\Eloquent\Relations\Descendants method 
protected function buildDictionary(Collection $results) fails.

Example: 
Look at below leads called with "descendents" relation **without WHERE clause** 

![image](https://user-images.githubusercontent.com/37204040/229035993-a7107a64-6ae2-4d05-8aed-fade27d3c2bb.png)

Now as I apply where clause

`$descendents = Lead::find(62740)->with(['descendents' => fn($q)=>$q->whereNull('agent_id')]);`

This results fails while fetching key.

![image](https://user-images.githubusercontent.com/37204040/229037890-d735ccb6-2acf-4599-9162-b47a5d3eac50.png)

This conditions fails
### if ($result->hasNestedPath()) {$key = $dictionary[$result->getFirstPathSegment()]->{$foreignKey}};

As due to where condition descendent with id 62962 will not be loaded and descendent with id 65600 is merged with 65962 due to same email id.

### Solution: 

When there is no descendent found with given key it should add to the parent search key. which is happening when I call "descendantsAndSelf" relation.

**Comment by YouMixx** [comment]
Everything works well! Thank you for your promptness.

**Comment by denisgoryaynov** [comment]
I am having the same issue ad @deepakchhapru,

this works: `auth()->user()->organization()->with('descendants')->first()`
this doesn't: `auth()->user()->organization()->with(['descendants' => fn($query) => $query->where('type', 'bar')])->first()`

It looks like that applying an sql condition when eager loading breaks the `buildDictionary` method.

**Comment by denisgoryaynov** [comment]
Hi @staudenmeir, I’m using the latest version which should be 1.13.4

**Comment by staudenmeir** [comment]
> this works: auth()->user()->organization()->with('descendants')->first()
> this doesn't: auth()->user()->organization()->with(['descendants' => fn($query) => $query->where('type', 'bar')])->first()

@denisgoryaynov Please create a new issue and share the SQL log from both queries.
